### ISSUE TITLE
Add flexibility to IAutofacMoqContainer

### ISSUE THREAD

**Issue by blaw2422** [patterns-group/code-patterns#109]
It would be nice for IAutofacMoqContainer's Mock call to have an optional boolean to be passed in that when true, will overwrite the registration, without checking for a current registration.

**Comment by TheTribe** [comment]
this really impacts IMoqContainer and this behavior should be true no matter what IoC flavor you're using.

**Comment by TheTribe** [comment]
Just checking... is this still perceived as a need? Did the latest beta release make this moot?

**Comment by blaw2422** [comment]
I don't believe this is necessary any longer.
