### ISSUE TITLE
Add fluent inheritance support to IoC packages and modules

### ISSUE THREAD

**Issue by TheTribe** [patterns-group/code-patterns#121]
Service-specific registrations should be done in a virtual method that returns the container framework's representation of the registration in-progress. This will allow for fluent method-chaining from inheritors:

``` csharp
public class ApplicationMappingModule : MappingModule
{
  public class ApplicationModule : MappingModule
  {
    protected override IRegistrationBuilder<MappingServices,
                      ConcreteReflectionActivatorData,
                      SingleRegistrationStyle> RegisterMappingServices()
    {
      return base.RegisterMappingServices()
                      .EnableInterfaceInterceptors()
                      .InterceptedBy(typeof(MappingInterceptor));
    }
  }
}
```

**Comment by jbatte47** [comment]
This should actually be:

``` csharp
public class ApplicationMappingModule : MappingModule
{
  public class ApplicationModule : MappingModule
  {
    protected override IRegistrationBuilder<object,
                      ReflectionActivatorData,
                      SingleRegistrationStyle> RegisterMappingServices()
    {
      return base.RegisterMappingServices()
                      .EnableInterfaceInterceptors()
                      .InterceptedBy(typeof(MappingInterceptor));
    }
  }
}
```

The difference is the first two type arguments in the `IRegistrationBuilder` instance being returned. Thanks to the covariance of the type arguments, we can specify `object` as the instance type, allowing us to use **any** registration call (as long as it is directly and not dynamically loaded) in the base type as well as any overrides. In the previous version of the sample, only the `MappingServices` type or its derived types may be registered in overrides.

**Comment by jbatte47** [comment]
After having put this into practice in other places, it's evident that this solution makes the module code itself quite hard to read. The code smell is too much for me so I'm closing this; I'll create a new issue that addresses this need while being less prescriptive.
