### ISSUE TITLE
Provide LinqPad-like "Dump" functionality for all objects.

### ISSUE THREAD

**Issue by jbatte47** [patterns-group/code-patterns#55]
Probably need to use the ObjectGraph concept for breaking a complex type up into an easily-serialized structure. May need to do some research on how best to represent that structure in a debug stream.

**Comment by prakash-patel** [comment]
I was researching about Dump() and i found this (http://stackoverflow.com/questions/1443548/printing-full-object-graph-using-c-sharp-and-reflection#answer-14498669) on stackoverflow.

**Comment by jbatte47** [comment]
Yeah, that thread has some interesting ideas... I wish the debug stream was capable of more than just raw text... I mean, I guess technically it is, but nothing reads it except for loggers and consoles, so raw text is the only thing that makes sense for a universal "Dump" outside of a specialized editor like LINQPad. Since you can use the [RazorEngine](https://github.com/Antaris/RazorEngine) so easily to create any string output imaginable based on an object instance, I'm actually thinking this needs to be dropped. I'm gonna go ahead and close it.
