### ISSUE TITLE
Age Calculation

### ISSUE THREAD

**Issue by jbatte47** [patterns-group/code-patterns#56]
Add an AsAge() method via extension to the DateTime type. This method should return a new structure, Age, that has a Years, Months, and Days value.

**Comment by chazt3n** [comment]
How do I assign this to me?

**Comment by jbatte47** [comment]
I just did a little googling and it appears you can't unless I add you as a direct contributor on this repo, but that defeats part of the coolness of us each having our own and going through the PR process. :(

**Comment by jbatte47** [comment]
you're a contributor now, but let's stick to the PR pipeline

**Comment by chazt3n** [comment]
Same as at work right?

Sent from my Windows Phone

**Comment by jbatte47** [comment]
sort of, but with one or two small differences; it's like if we all just had our private repo and there was no repo for the team. instead of pushing / pulling with jbatte47/code-patterns.git, you'll use chazt3n/code-patterns.git. then when you've got a branch ready for merge, submit a PR to my repo's dev branch using the site.

**Comment by jbatte47** [comment]
Also, get with Igor on this one; he's got some sort of crazy test case that invalidates the algorithm I have for this. He found the failure a couple of weeks ago and I haven't had a chance to write anything else since then... still, here's what I was able to come up with, in the form of some LINQPad code. Hopefully it'll at least get you going in the right direction:

``` csharp
TimeSpan ageAsTimeSpan = DateTime.Now - new DateTime(1979, 8, 27);
DateTime ageAsDateTime = DateTime.MinValue.Add(ageAsTimeSpan);
var age = new
{
    Years = ageAsDateTime.Year - 1,
    Months = ageAsDateTime.Month - 1,
    Days = ageAsDateTime.Day - 1
};

age.Dump("some old fart's age in years, months, and days");
```

**Comment by chazt3n** [comment]
Ok grabbing this code, if !branch.Exists I'm going to make it, and going to send Igor an email.

**Comment by chazt3n** [comment]
ermahgerd this dood is olden

**Comment by jbatte47** [comment]
oh, hardy har har. yeah I still haven't found Igor's email; I'll fwd to you if I come across it.

**Comment by chazt3n** [comment]
Sounds good, this is going to be my first contribution to Code-Patterns! (And on Github in general actually)

**Comment by chazt3n** [comment]
Where should the Age model go?

**Comment by jbatte47** [comment]
New namespace: Patterns.Values. Also, make sure it's a struct, not a class. Also, scope creep! It should be immutable, so it'll have to be fed all its values in its constructor, and at that point we should provide operator overloads so you can produce new values, not to mention make Age-to-Age comparisons. The operators that make sense to me are `+`, `-`, `==`, `!=`, `<`, `>`, `<=`, `>=`, `+=`, and `-=`. There's [more info on MSDN](http://msdn.microsoft.com/en-us/library/8edha89s.aspx) about it.

**Comment by jbatte47** [comment]
It should also come with an [implicit conversion operator](http://msdn.microsoft.com/en-us/library/z5z9kes2.aspx) for `TimeSpan`, but I think it would be one-way, since the rule for conversion operators is "no data loss". So just something like:

``` csharp
public static implicit operator Age(TimeSpan value)
{
  //TODO: calculate and return Age using formula
}
```

But no need for one back to `TimeSpan` since you'd lose everything after the day value. Plus, the unit values get skewed.

**Comment by jbatte47** [comment]
Why don't we list my last two comments as future issues; just making the type a struct is good enough for this ticket. I'll create the new issues now and we'll add them to a milestone whenever we get to it

**Comment by jlmorgan** [comment]
What about ++ and --? You can decrement and increment things like Age.

Justin Morgan

**Comment by jbatte47** [comment]
Sort of, but what are you incrementing / decrementing? The days? Months? Years? With `++` and `--` you're implicitly adding / subtracting by one unit... but what is one Age? With `+=` and `-=` you are incrementing / decrementing by another Age value, so that makes sense.

**Comment by jlmorgan** [comment]
Pff. Planck time of course. Duh.

https://en.wikipedia.org/wiki/Planck_time

Justin Morgan

**Comment by chazt3n** [comment]
Sounds good to me, let me get a PR polished up
