### ISSUE TITLE
All injectable services provided by Patterns need to be easily available in whatever container the consuming developer is using.

### ISSUE THREAD

**Issue by jbatte47** [patterns-group/code-patterns#62]
Right now the enterprise-stable and extremely popular container flavors are:
1. Ninject
2. Autofac
3. Castle Windsor

Take `Patterns.Autofac` and `Patterns.Testing.Autofac` as a partial template; Autofac uses `Module` to package registration instructions; Ninject uses a type by the same name, and Windsor uses what they call an `Installer`. One of each of these needs to be available for every injectable component or service in all non-container-specific Patterns assemblies. 

AC:

Each of the following projects successfully builds a NuGet package:
1. Patterns.Autofac
2. Patterns.Ninject
3. Patterns.Windsor
4. Patterns.Testing.Autofac
5. Patterns.Testing.Ninject
6. Patterns.Testing.Windsor

Each package must expose a single module / installer for assembly-wide component registration as well as namespace-wide extensions for a la cart registrations. In the case of Patterns.Testing supportive packages, `IMoqContainer` must be implemented in each one -- research required.

**Comment by TheTribe** [comment]
It appears that Autofac's `IRegistrationSource` is a container-specific feature that Ninject and Windsor don't have good (or any) support for. Not going to worry about trying to simulate that functionality in the other assemblies.

**Comment by TheTribe** [comment]
The scope of this has gotten out of hand. Plus, with the introduction of issue #119, the requirements here would likely have changed. I'm going to remove the milestone assignment from this issue, and we'll refine it and schedule it later.

**Comment by jbatte47** [comment]
No need to hang onto this change set any longer; origin has drifted a lot since then and the requirements are already split up. I'm closing this.
