### ISSUE TITLE
Age should provide implicit conversion from TimeSpan

### ISSUE THREAD

**Issue by jbatte47** [patterns-group/code-patterns#75]
lifted from issue #56 :

It should also come with an [implicit conversion operator](http://msdn.microsoft.com/en-us/library/z5z9kes2.aspx) for `TimeSpan`, but I think it would be one-way, since the rule for conversion operators is "no data loss". So just something like:

``` csharp
public static implicit operator Age(TimeSpan value)
{
  //TODO: calculate and return Age using formula
}
```

But no need for one back to `TimeSpan` since you'd lose everything after the day value. Plus, the unit values get skewed.

**Comment by TheTribe** [comment]
Depends on #56
