### ISSUE TITLE
Age should provide overloaded operators

### ISSUE THREAD

**Issue by jbatte47** [patterns-group/code-patterns#76]
Lifted from #56 :

It should be immutable, so it'll have to be fed all its values in its constructor, and at that point we should provide operator overloads so you can produce new values, not to mention make Age-to-Age comparisons. The operators that make sense to me are `+`, `-`, `==`, `!=`, `<`, `>`, `<=`, `>=`, `+=`, and `-=`. There's [more info on MSDN](http://msdn.microsoft.com/en-us/library/8edha89s.aspx) about it.

**Comment by TheTribe** [comment]
Depends on #56
